#!/usr/bin/env bash
set -euo pipefail

report="LAUNCH_EXECUTION_STATUS.md"

bundle_id_expected="app.murmur.Murmur"

has() { rg -n --fixed-strings "$2" "$1" >/dev/null; }

status_line() {
  local state="$1"; shift
  printf -- "- [%s] %s\n" "$state" "$*" >> "$report"
}

: > "$report"
cat >> "$report" <<'HDR'
# Murmur Launch Execution Status

Generated by `scripts_launch_preflight.sh`.

Legend:
- [x] completed locally by agent
- [ ] pending (requires external account action)

## Local preflight checks
HDR

if has project.yml "$bundle_id_expected"; then
  status_line x "Bundle identifier present in project.yml: $bundle_id_expected"
else
  status_line " " "Bundle identifier missing in project.yml: $bundle_id_expected"
fi

if [ -f Gemfile ]; then
  status_line x "Gemfile exists for fastlane dependency management"
else
  status_line " " "Gemfile missing"
fi

if [ -f APP_STORE_CONNECT_CHECKLIST.md ] && [ -f WINDOWS_TO_APPSTORE.md ] && [ -f PUBLISHING.md ]; then
  status_line x "Core publishing runbooks present"
else
  status_line " " "One or more publishing runbooks missing"
fi

cat >> "$report" <<'HDR'

## External actions still required (cannot be automated from this environment)
- [ ] Apple Developer Program enrollment/verification completion
- [ ] App Store Connect API key generation and secure key download (.p8)
- [ ] GitHub repository secrets population with real credential values
- [ ] One-time certificate/profile bootstrap (`fastlane match appstore`) tied to your Apple account
- [ ] TestFlight build processing confirmation in App Store Connect
- [ ] Final legal submission click in App Store Connect

## Next operator step
Run:

```bash
bash scripts_launch_preflight.sh
```

then follow `LAUNCH_MASTER_PLAN.md` section 5 phases B-F with real account credentials.
HDR

echo "Wrote $report"
